// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScreen(arg1) {
  return window['go']['pageUtils']['Categories']['GetScreen'](arg1);
}

export function LoadCategories() {
  return window['go']['pageUtils']['Categories']['LoadCategories']();
}
