// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pageUtils} from '../models';

export function GetScreen(arg1:number):Promise<pageUtils.Screen>;

export function LoadCategories():Promise<pageUtils.CategoryMembers>;
