// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePage(arg1) {
  return window['go']['main']['App']['GeneratePage'](arg1);
}

export function SearchForPage(arg1) {
  return window['go']['main']['App']['SearchForPage'](arg1);
}
