// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GeneratePage(arg1:string):Promise<main.PageInfo>;

export function LoadPages():Promise<main.CategoryMembers>;

export function SearchForPage(arg1:string):Promise<any>;
