// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {pageUtils} from '../models';

export function GeneratePage(arg1:number):Promise<main.PageInfo>;

export function SearchForPage(arg1:string):Promise<pageUtils.RestPageSearch>;
