// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetScreen(arg1:number):Promise<main.Screen>;

export function LoadCategories():Promise<main.CategoryMembers>;
