# Stock workflow from Wails

name: Wails build

on: push

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "quDnD"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "quDnD"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "quDnD"
            platform: "darwin/universal"
            os: "macos-latest"
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"
      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install libwebkit2gtk-4.0-dev
          fi
        shell: bash
      - name: Build quDnD
        run: wails build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: quDnD-build
          path: build/bin/quDnD*
