# Stock workflow from Wails

name: Wails build

on: push

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "quDnD-linux"
            platform: "linux/amd64"
            os: "ubuntu-22.04"
          - name: "quDnD-windows"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "quDnD-macos"
            platform: "darwin/universal"
            os: "macos-latest"
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"
      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update
              sudo apt-get install build-essential libgtk-3-dev libwebkitgtk-6.0-dev libwebkitgtk-6.0-4 libwebkit2gtk-4.0-dev webkit2gtk-4.0
              fi
        shell: bash
      - name: Build quDnD
        run: cd ${{ github.workspace }} && wails build
      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: quDnD-linux
          path: ${{ github.workspace }}/build/bin/quDnD*
      - name: Upload MacOS build
        uses: actions/upload-artifact@v4
        with:
          name: quDnD-macos
          path: ${{ github.workspace }}/build/bin/flipfloppy/quDnD.app
      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: quDnD-build
          path: ${{ github.workspace }}/build/bin/quDnD*
